### ISSUE TITLE
Pairing failes with DBusExecutionException: Authentication Canceled

### ISSUE THREAD

**Issue by ghost** [hypfvieh/bluez-dbus#33]
I try to pair a device, but this fails with the following Exception. How can I pass authentication data or is this related to a problem with dbus?

org.freedesktop.dbus.exceptions.DBusExecutionException: Authentication Canceled
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.freedesktop.dbus.errors.Error.getException(Error.java:157)
	at org.freedesktop.dbus.errors.Error.throwException(Error.java:187)
	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:164)
	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:228)
	at com.sun.proxy.$Proxy61.Pair(Unknown Source)
	at com.github.hypfvieh.bluetooth.wrapper.BluetoothDevice.pair(BluetoothDevice.java:507)

**Comment by ghost** [comment]
The device should be in pairing mode (press pairing button or other type)!
