### ISSUE TITLE
How to pair a new device (phone) using bluez-dbus

### ISSUE THREAD

**Issue by yyvus** [hypfvieh/bluez-dbus#41]
Hi,

I am trying to put in place a java app that allows to pair and connect a smart phone to my linux computer. I have been able to scan, find the MAC address and, if already paired, connect. My troubles are with the pairing protocol.

When doing it using the terminal I have followed the following protocol:
```
hcitool scan  # to get the MAC address of your device
bluetoothctl
agent on
scan on  # wait for your device's address to show up here
scan off
trust MAC_ADDRESS
pair MAC_ADDRRESS
connect MAC_ADDRESS
```
which during pairing requires a confirmation. This confirmation is to check that pairing isdone between the corresponding devices, which share the same temporary code displayed on my phone. But when trying to pair the device using `bluez-dbus`, using this code, it fails:
```
                var deviceManager = DeviceManager.createInstance( false );
		var listDevices = deviceManager.getDevices();
		
		var phone = listDevices.stream().filter( d -> d.getName().equals( "Phone_Name" ) ).findFirst().orElse( null );
		if( phone == null ){
			System.out.println( "not found" );
		}else{
			System.out.println( "Pairing/Connecting ..." );
			if( !phone.isPaired() ) {
				phone.setTrusted( true );
				phone.pair();
			}
			phone.connect();
		}

		deviceManager.closeConnection();
```
Here I have no way to confirm that the device is receiving the correct pairing code.
Any clue?

Thanks

**Comment by yyvus** [comment]
See #13 and the [AgentManagerExample.java](https://github.com/hypfvieh/sandbox/blob/master/src/main/java/com/github/hypfvieh/sandbox/bluez/AgentManagerExample.java). 
In my case the Agent example fails to connect to the device with the error:
```
Retrieving AgentManager1
Creating Agent1
Registering Agent1 on AgentManager1
Registering Agent1 as default agent
Exporting Agent1 to Dbus
Exception in thread "main" org.freedesktop.dbus.exceptions.DBusExecutionException: Software caused connection abort
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.freedesktop.dbus.errors.Error.getException(Error.java:157)
	at org.freedesktop.dbus.errors.Error.throwException(Error.java:187)
	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:164)
	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:228)
	at com.sun.proxy.$Proxy24.Connect(Unknown Source)
	at Main.fullProtocol(Main.java:46)
	at Main.main(Main.java:82)
```
which smells like a timeout error...

**Comment by yyvus** [comment]
It works, the Device was already paired and hence the Exception mentioned above.
