### ISSUE TITLE
"could not load FFI provider jnr.ffi.provider.jffi.Provider" when using module-info.java

### ISSUE THREAD

**Issue by vria** [hypfvieh/bluez-dbus#47]
Hi, 

first of all thank you for great lib.
It worked very well until I added module-info.java to my client code. Suddenly I got this error:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
	at jnr.ffi@2.1.15/jnr.ffi.provider.InvalidRuntime.newLoadError(InvalidRuntime.java:101)
	at jnr.ffi@2.1.15/jnr.ffi.provider.InvalidRuntime.findType(InvalidRuntime.java:42)
	at jnr.ffi@2.1.15/jnr.ffi.Struct$NumberField.<init>(Struct.java:872)
	at jnr.ffi@2.1.15/jnr.ffi.Struct$Unsigned16.<init>(Struct.java:1240)
	at jnr.unixsocket@0.33/jnr.unixsocket.SockAddrUnix$DefaultSockAddrUnix.<init>(SockAddrUnix.java:209)
	at jnr.unixsocket@0.33/jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174)
	at jnr.unixsocket@0.33/jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:53)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.transports.UnixSocketTransport.<init>(UnixSocketTransport.java:32)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.transports.TransportFactory.createTransport(TransportFactory.java:37)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:161)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:334)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:149)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:169)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:219)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at bluez.dbus@0.1.3/com.github.hypfvieh.bluetooth.DeviceManager.createInstance(DeviceManager.java:74)
	at ...
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/x86_64-Linux/libjffi-1.2.so, /jni/x86_64-Linux/libjffi-1.2.so]
	at jffi@1.2.23/com.kenai.jffi.internal.StubLoader.getStubLibraryStream(StubLoader.java:450)
	at jffi@1.2.23/com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:375)
	at jffi@1.2.23/com.kenai.jffi.internal.StubLoader.load(StubLoader.java:278)
	at jffi@1.2.23/com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:487)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at jffi@1.2.23/com.kenai.jffi.Init.load(Init.java:68)
	at jffi@1.2.23/com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
	at jffi@1.2.23/com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
	at jffi@1.2.23/com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
	at jffi@1.2.23/com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
	at jffi@1.2.23/com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
	at jffi@1.2.23/com.kenai.jffi.Type.resolveSize(Type.java:155)
	at jffi@1.2.23/com.kenai.jffi.Type.size(Type.java:138)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
	at jnr.ffi@2.1.15/jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
	at jnr.ffi@2.1.15/jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at jnr.ffi@2.1.15/jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
	at jnr.ffi@2.1.15/jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
	at jnr.ffi@2.1.15/jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
	at jnr.ffi@2.1.15/jnr.ffi.Runtime$SingletonHolder.<clinit>(Runtime.java:82)
	at jnr.ffi@2.1.15/jnr.ffi.Runtime.getSystemRuntime(Runtime.java:67)
	at jnr.unixsocket@0.33/jnr.unixsocket.SockAddrUnix.<init>(SockAddrUnix.java:46)
	at jnr.unixsocket@0.33/jnr.unixsocket.SockAddrUnix$DefaultSockAddrUnix.<init>(SockAddrUnix.java:208)
	at jnr.unixsocket@0.33/jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174)
	at jnr.unixsocket@0.33/jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:53)
	at dbus.java@3.2.3/org.freedesktop.dbus.connections.transports.UnixSocketTransport.<init>(UnixSocketTransport.java:32)
	at ...

The method caused this error is :
```java
DeviceManager.createInstance(false);
```

I tried to require everything related to this error in the module-info.java without success:

```java
module org.example {
    requires dbus.java;
    requires dbus.java.nativefd;
    requires bluecove.linux.custom;
    requires bluez.dbus;
    requires jnr.ffi;
    requires jnr.x86asm;
    requires jnr.posix;
    requires jnr.enxio;
    requires jnr.unixsocket;
    requires jnr.constants;
    requires jnr.a64asm;
}
```

Thank you in advance.

**Comment by hypfvieh** [comment]
Sorry can't help you here. 

I don't use the module-stuff in any of my libs (I don't like it, it always causes pain, solves nothing and puts you in modules+classpath hell)...

Also jnr-ffi does not use java-modules, so I guess there is a pretty big chance that the application will throw exception on runtime if you try to use modules in your application...
